version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: magang_hunter_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passwordkuat123
      POSTGRES_DB: magang_hunter
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: